version: "3"

services:
  jupyterlab:
    build: ./docker
    user: root
    environment:
      NB_UID: 1000
      NB_GID: 100
      GRANT_SUDO: "yes"
    volumes:
      - .:/code
    tty: true
    privileged: true
    ports:
      - 8888:8888
    restart: unless-stopped
    command: start.sh jupyter lab --NotebookApp.token=''